# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('checksum', models.BinaryField(null=True)),
                ('state', models.CharField(choices=[('OK', 'OK'), ('UPDATED', 'UPDATED'), ('FILESYSTEMERROR', 'FILESYSTEMERROR'), ('CRYPTOERROR', 'CRYPTOERROR')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=128, unique=True)),
                ('descr', models.TextField(blank=True)),
                ('registred', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(choices=[('CKECK', 'CHECK'), ('UPDATE', 'UPDATE'), ('NEWCLIENT', 'NEWCLIENT'), ('NEWFILESET', 'NEWFILESET')], max_length=32)),
                ('result', models.CharField(blank=True, choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=32, null=True)),
                ('registred', models.DateTimeField(auto_now_add=True)),
                ('badFiles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hashez.BadFiles')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashez.Client')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('checksum', models.BinaryField(null=True)),
                ('state', models.CharField(choices=[('OK', 'OK'), ('UPDATED', 'UPDATED'), ('FILESYSTEMERROR', 'FILESYSTEMERROR'), ('CRYPTOERROR', 'CRYPTOERROR')], max_length=32)),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FileSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registred', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashez.Client')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='fileSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashez.FileSet'),
        ),
        migrations.AddField(
            model_name='event',
            name='fileSet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hashez.FileSet'),
        ),
        migrations.AddField(
            model_name='badfiles',
            name='fileSet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hashez.FileSet'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('path', 'fileSet')]),
        ),
    ]
