# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=128, unique=True)),
                ('descr', models.TextField(blank=True)),
                ('registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eType', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=32)),
                ('lasttime', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashez.Client')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=512)),
                ('checksum', models.BinaryField(null=True)),
                ('state', models.CharField(choices=[('OK', 'OK'), ('UPDATED', 'UPDATED'), ('FILESYSTEMERROR', 'FILESYSTEMERROR'), ('CRYPTOERROR', 'CRYPTOERROR'), ('EMPTY', 'EMPTY')], max_length=32)),
                ('registration', models.DateTimeField(auto_now_add=True)),
                ('recalculate', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashez.Client')),
            ],
        ),
    ]
